### ISSUE TITLE
about int64 bug,when int variable set millisecond value then var_dump variable will see the  type change to float type

### ISSUE THREAD

**Issue by busyfree** [protobuf-php/protobuf#9] opened 2016-06-17 12:31 UTC
## proto file define

``` proto
message PayloadHead {
    optional sint64 timestamp = 10; 
    optional sint32 nonce = 11;
    optional string signature = 12;
}
```

---
## protobuf-php generate file

``` php
<?php
/**
 * Protobuf message : pb_global.PayloadHead
 */
class PayloadHead extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * timestamp optional sint64 = 10
     *
     * @var int
     */
    protected $timestamp = null;

   /**
     * nonce optional sint32 = 11
     *
     * @var int
     */
    protected $nonce = null;

    /**
     * signature optional string = 12
     *
     * @var string
     */
    protected $signature = null;
}
```

---
## define the variable 

``` php
<?php
public function payload()
{
       $reqPayload = new Payload();
        $head = new PayloadHead();
        $timestamp = 1466165225000; //here int value
        $head->setTimestamp($timestamp);
        var_dump($head);
}
```

---
## var_dump output

```
object(LivingPB\Payload\PayloadHead)#231 (17) {
  ["unknownFieldSet":protected]=>
  NULL
  ["timestamp":protected]=>
  **float**(1466165225000)  //type changed
  ["nonce":protected]=>
  int(312606)
  ["signature":protected]=>
  string(40) "667fdc90ac64aa24a72ea444bffa532e96b3b5e6"
}
```

---

please check this issue.
thanks

**Comment by FabioBatSilva** [comment] 2016-06-18 15:58
Hi @geekcode , 

Sorry but I cannot reproduce this issue : https://github.com/protobuf-php/protobuf/commit/306020f6639fc4257d62c9870998a17a786cb5bb

A failing test case would be great !

**Comment by busyfree** [comment] 2016-06-19 09:00
Hi FabioBatSilva,
in protobuf-php/protobuf tests folder missing some requrie file ,so test case i can't run.now i create a test.proto  file to test pb message object.

[test.proto.txt](https://github.com/protobuf-php/protobuf/files/322180/test.proto.txt)
[TestInt.php.txt](https://github.com/protobuf-php/protobuf/files/322182/TestInt.php.txt)
[Test.php.txt](https://github.com/protobuf-php/protobuf/files/322185/Test.php.txt)

---

attach file extension need remove the .txt char.
please run this code and check the output.
my php version is PHP 5.5.10 and with gmp on centos i686.
thanks

**Comment by FabioBatSilva** [comment] 2016-06-19 17:14
@geekcode If PHP encounters a number beyond the bounds of the integer type, it will be interpreted as a float instead. if you are running it in a 32 bit kernel the max int will be `2147483647`

See : http://php.net/manual/en/language.types.integer.php

**Comment by busyfree** [comment] 2016-06-19 17:27
thanks

**Closed as completed** 2016-06-19 17:26 UTC
Labels: invalid, Can't reproduce, Awaiting feedback
